
{{- if .Values.server.disruption }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "doorkeeper.fullname" . }}
  labels:
    {{- include "doorkeeper.labels" . | nindent 4 }}
    {{- with .Values.server.extraLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}

  {{- with .Values.server.disruption.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}


spec:
  {{- with .Values.server.disruption.minAvailable }}
  minAvailable: {{ . }}
  {{- end }}

  {{- with .Values.server.disruption.maxUnavailable }}
  maxUnavailable: {{ . }}
  {{- end }}

  selector:
    matchLabels:
      {{- include "doorkeeper.selectorLabels" . | nindent 4 }}
      {{- with .Values.server.extraLabels }}
      {{- toYaml . | nindent 8 }}
      {{- end }}
---
{{- end }}
