apiVersion: v1
kind: Service
metadata:
  name: {{ include "doorkeeper.fullname" . }}
  labels:
    {{- include "doorkeeper.labels" . | nindent 4 }}
  {{- with .Values.server.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:

  {{- with .Values.server.service.type }}
  type: {{ . }}
  {{- end }}

  {{- with .Values.server.service.clusterIP }}
  clusterIP: {{ . }}
  {{- end }}

  {{- if (semverCompare ">= 1.23-0" .Capabilities.KubeVersion.Version) }}
  {{- with .Values.server.service.ipFamilyPolicy }}
  ipFamilyPolicy: {{ . }}
  {{- end }}
  {{- with .Values.server.service.ipFamilies }}
  ipFamilies: {{ . | toYaml | nindent 2 }}
  {{- end }}
  {{- end }}

  {{- with .Values.server.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ . }}
  {{- end }}

  # We want the servers to become available even if they're not ready
  # since this DNS is also used for join operations.
  {{- with .Values.server.service.publishNotReadyAddresses }}
  publishNotReadyAddresses: {{ . }}
  {{- end}}

  ports:
  {{ range $key, $value := .Values.server.service.ports }}
    - name: {{ $value.name }}
      port: {{ $value.port }}
      targetPort: {{ $value.targetPort }}

      {{- with $value.protocol }}
      protocol: {{ . }}
      {{- end }}

      {{- if and ($value.nodePort) (eq ($.Values.server.service.type | toString) "NodePort") }}
      nodePort: {{ $value.nodePort }}
      {{- end }}
  {{- end}}

  selector:
    {{- include "doorkeeper.selectorLabels" . | nindent 4 }}
